### PR TITLE
Run aarch64 and ppc64le on azure

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

aarch64 and ppc64le weren't build in previous [PR](https://github.com/conda-forge/cpptango-feedstock/pull/17). Trying to bump the build number to see if a new pipeline will help.
This is not supposed to be merged as is.

Update: forcing to build on azure (this is slow but more reliable than Travis).

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
@conda-forge-admin, I PR was merged last week to rebuild the package for aarch64 and ppc64le: https://github.com/conda-forge/cpptango-feedstock/pull/16 It worked fine and was merged.

Today, when I made a PR to release a new version https://github.com/conda-forge/cpptango-feedstock/pull/17, only Azure Pipelines were run. No Travis CI. The new arch aren't built.

Is something missing in the feedstock?
I opened this PR to check. I can see that Travis is still not run.

**Comment by hmaarrfk** [comment]
Travis has been having intermittent outages. I recommend that you move to to azure for al builds if possible.

Since you can already cross compile OSX-arm. it usually is pretty easy to cross compile LINUX too.

Add
```
build_platform:
  osx_arm64: osx_64
  linux_pcc64le: linux_64
  linux_aarch64: linux_64
```

to https://github.com/beenje/cpptango-feedstock/blob/build-missing-arch/conda-forge.yml#L2

and rerender. it should be able to build things on azure quickly.

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
Thanks @hmaarrfk! I had issue rendering the feedstock with your suggestion. It worked by forcing the providers:

```yaml
provider:
   linux_aarch64: azure
   linux_ppc64le: azure
```

I saw that in https://github.com/conda-forge/scotch-feedstock/pull/70/commits/8559c8abc512e6155e9df828cb3c9bce9a59fb0f when looking at https://github.com/conda-forge/conda-forge.github.io/issues/1875

**Pull request merged**
