### PR TITLE
Test windows support

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is for testing windows build.
I built from https://gitlab.com/tango-controls/cppTango/-/merge_requests/827

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
OK, I wanted to test the build, but it wasn't triggered due to merge conflict :-(
I'll have to see how to skip the debug package on windows.

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
The windows build was successful!

Linux failed because I set the package version to `9.3.5dev1` but that doesn't match the lib version (still `9.3.4`).
Not sure how we should handle "dev" version number. Can we patch that in the conda recipe?

Btw, I created the "dev" branch to be able to create dev conda package as described here: https://conda-forge.org/docs/maintainer/knowledge_base.html#creating-a-pre-release-build

**Comment by t-b** [comment]
@beenje Nice work. Does the windows package include the pdb files? These hold the splitoff debug info. The best option would probably be to have those in a separate debug package like you do on linux. PDB files are only available when you build the shared libraries, which I think you do.

**Comment by beenje** [comment]
Yes, the pdb file is there:

```
Library
├── bin
│   ├── tango.dll
│   └── tango.pdb
├── include
│   ...
└── lib
    └── tango.lib
```

I will split the package in 2 then.
Note that I build with `CMAKE_BUILD_TYPE=Release`. IIRC I couldn't build with `Debug` on windows because that would require the dependencies to have been built with Debug as well and the conda packages aren't as far as I can tell.

**Comment by beenje** [comment]
Any suggestion about the version number to use if we want to build a `dev` version?

**Comment by t-b** [comment]
> Any suggestion about the version number to use if we want to build a dev version?

You mean from cppTango main branch? I'm not sure I'm in favour of that, people will probably expect that we don't break ABI every week.

**Comment by beenje** [comment]
Windows installs many files directly under `Library/include` (and not only `Library/include/tango`). Any specific reason for that?

When creating a package, `conda-build` usually automatically adds all the new files copied under `PREFIX`.
But when specifying the files to include in a subpackage, that's not the case. I had to create a small script to record the files (from the dependencies) present and remove them so they aren't packaged with cpptango.

**Comment by beenje** [comment]
> > Any suggestion about the version number to use if we want to build a dev version?
> 
> You mean from cppTango main branch? I'm not sure I'm in favour of that, people will probably expect that we don't break ABI every week.

I was thinking about the current PR. What if we want to release that package for testing purpose? I did the PR to the `dev` branch, meaning that the package would be published to a specific channel (you would have to use `conda install -c conda-forge/label/cpptango_dev cpptango` to install it). No risk that someone installs it by mistake. If you decide to install a "dev" package you should know what you are doing. I assume it could also be used for the main branch for testing purpose.

The package version could be `9.3.5.dev1`.
In that case what should be the version of the lib? `9.3.5`(next release)? I don't think `9.3.5.dev1` is supported.

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
@t-b I updated the recipe using the last [commit](https://gitlab.com/tango-controls/cppTango/-/commit/328b93be81ad149055a5eaeca290b2755ff7a0a5) from https://gitlab.com/tango-controls/cppTango/-/merge_requests/827

cpptango-dbg includes `Library/bin/tango.pdb`.

cpptango includes:
      - Library/bin/tango.dll
      - Library/lib/tango.lib
      - Library/include/tango
      - Library/include/pkgconfig/tango.pc

**Comment by beenje** [comment]
Closing in favour of https://github.com/conda-forge/cpptango-feedstock/pull/7

**Pull request closed without merging**
